# Configuration Railway pour déploiement automatique
# https://railway.app/

[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"

[deploy]
startCommand = "python -m uvicorn server:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[build.buildCommand]]
command = "cd backend && pip install -r requirements.txt"

[env]
PORT = { value = "8000" }
HOST = { value = "0.0.0.0" }
ENV = { value = "production" }
DEBUG = { value = "False" }

# Variables à définir dans Railway Dashboard:
# - SECRET_KEY
# - JWT_SECRET_KEY
# - ENCRYPTION_KEY
# - OPENROUTER_API_KEY
# - REDIS_URL (fourni automatiquement par Railway si Redis ajouté)
# - ALLOWED_ORIGINS

[healthcheck]
path = "/api/health"
timeout = 10
interval = 30
